jdbc:
  url: jdbc:mysql://localhost:3306/YIDAGV?zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Taipei&characterEncoding=utf-8&useUnicode=true
  username: root
  password: 12345678

agvControl:
#  url: http://192.168.0.100:20100
#  url: http://10.11.33.232:20100
#  url: http://172.1.122.190:20100
  url: http://localhost:20100

agv:
  low_battery: 80  # AGV電量低於多少時，派遣回待命點
  low_battery_duration: 60  # AGV電量低於多少時，派遣回待命點
  task_exception_option: 1 # AGV上線並且實例有任務時TrafficControl回報沒有執行任務時該: 0刪除任務 1重新派遣

caller:
  offline_duration: 20 # 離線多久警報

http:
  max_retry: 3 # 重新發送AGV命令次數